name: Run all tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install acme
      run: |
        sudo apt-get install acme

    - name: Re-assemble original binary
      run: |
        make list

    - name: 'Upload build artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
            interpod-1.6.bin
            interpod-1.6.lst
