name: Run all tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install acme
      run: |
        wget https://www.mirrorservice.org/sites/ftp.cs.vu.nl/pub/minix/distfiles/backup/acme091src.tar.gz
        tar xzf acme091src.tar.gz
        make -C acme091/src install BINDIR=$PWD/acme-bin
        echo "$PWD/acme-bin" >> $GITHUB_PATH

    - name: Re-assemble original binary
      run: |
        acme -o out.bin interpod-1.6.asm
        diff out.bin interpod-1.6.bin
